version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "PASSWORD"
      MYSQL_DATABASE: contact_manager

    volumes:
      - ./mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "PASSWORD"

    depends_on:
      - mysql

  springboot:
    build: .
    container_name: contact_manager
    environment:
      SERVER_PORT: 8081
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: contact_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: "PASSWORD"
      EMAIL_HOST: HOSTEMAIL@gmail.com 
      EMAIL_POST: 587
      EMAIL_USERNAME: smtp@mailtrap.io
      EMAIL_PASSWORD: "EMAIL_PASSWORD_SMTP"
      EMAIL_DOMAIN: helo@demomailtrap.co
      CLOUDINARY_API_KEY: 489764916498244
      CLOUDINARY_SECRET_KEY: "CLOUDINARY_SECRET_KEY"
      CLOUDINARY_NAME: "CLOUDINARY_NAME"

    ports:
      - "8082:8080"

    depends_on:
      - mysql

volumes:
  mysql_data



