version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: contact_manager

    volumes:
      - ./mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: PASSWORD

    depends_on:
      - mysql

  springboot:
    build: .
    container_name: contact_manager
    environment:
      SERVER_PORT: 8081
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: contact_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: PASSWOED
      EMAIL_HOST: siddharth1977@gmail.com 
      EMAIL_POST: 587
      EMAIL_USERNAME: smtp@mailtrap.io
      EMAIL_PASSWORD: a6ffee024b993fef749ed64b1d00d35e
      EMAIL_DOMAIN: helo@demomailtrap.co
      CLOUDINARY_API_KEY: 489764916498244
      CLOUDINARY_SECRET_KEY: iV90k_ktIi8r6gwpFnl5Uja_m60
      CLOUDINARY_NAME: diqvjs6zz

    ports:
      - "8082:8080"

    depends_on:
      - mysql

volumes:
  mysql_data



